import { defineStore } from 'pinia'

export const useItems = defineStore('itemStore', {
    state: () => {
        return {
            schemes: [
                {
                    id: 0,
                    name: "Archetype Name",
                    fieldTypes: [
                        0,
                        1,
                        2
                    ],
                    fieldNames: [
                        "field1",
                        "field2",
                        "field3"
                    ],
                    items: [
                        [
                            "value1",
                            "value2",
                            "value3"
                        ],
                        [
                            "value4",
                            "value5",
                            "value6"
                        ],
                        [
                            "value7",
                            "value8",
                            "value9"
                        ],
                        [
                            "value4",
                            "value5",
                            "value6"
                        ],
                        [
                            "value7",
                            "value8",
                            "value9"
                        ],
                        [
                            "value4",
                            "value5",
                            "value6"
                        ],
                        [
                            "value7",
                            "value8",
                            "value9"
                        ],
                        [
                            "value4",
                            "value5",
                            "value6"
                        ],
                        [
                            "value7",
                            "value8",
                            "value9"
                        ],
                        [
                            "value4",
                            "value5",
                            "value6"
                        ],
                        [
                            "value7",
                            "value8",
                            "value9"
                        ],
                        [
                            "value4",
                            "value5",
                            "value6"
                        ],
                        [
                            "value7",
                            "value8",
                            "value9"
                        ],
                        [
                            "value4",
                            "value5",
                            "value6"
                        ],
                        [
                            "value7",
                            "value8",
                            "value9"
                        ],
                        [
                            "value4",
                            "value5",
                            "value6"
                        ],
                        [
                            "value7",
                            "value8",
                            "value9"
                        ],
                        [
                            "value4",
                            "value5",
                            "value6"
                        ],
                        [
                            "value7",
                            "value8",
                            "value9"
                        ],
                        [
                            "value4",
                            "value5",
                            "value6"
                        ],
                        [
                            "value7",
                            "value8",
                            "value9"
                        ],
                        [
                            "value4",
                            "value5",
                            "value6"
                        ],
                        [
                            "value7",
                            "value8",
                            "value9"
                        ],
                        [
                            "value4",
                            "value5",
                            "value6"
                        ],
                        [
                            "value7",
                            "value8",
                            "value9"
                        ]
                    ]
                },
                {
                    id: 1,
                    name: "Archetype Name 2",
                    fieldTypes: [
                        0,
                        1,
                        2,
                        3
                    ],
                    fieldNames: [
                        "field1",
                        "field2",
                        "field3",
                        "field4"
                    ],
                    items: [
                        [
                            "value1",
                            "value2",
                            "value3",
                            "value4"
                        ],
                        [
                            "value4",
                            "value5",
                            "value6",
                            "value4"
                        ],
                        [
                            "value7",
                            "value8",
                            "value9",
                            "value4"
                        ],
                        [
                            "value10",
                            "value11",
                            "value12",
                            "value4"
                        ],
                        [
                            "value10",
                            "value11",
                            "value12",
                            "value4"
                        ],
                        [
                            "value10",
                            "value11",
                            "value12",
                            "value4"
                        ],
                        [
                            "value7",
                            "value8",
                            "value9",
                            "value4"
                        ],
                        [
                            "value10",
                            "value11",
                            "value12",
                            "value4"
                        ],
                        [
                            "value10",
                            "value11",
                            "value12",
                            "value4"
                        ],
                        [
                            "value10",
                            "value11",
                            "value12",
                            "value4"
                        ],
                        [
                            "value7",
                            "value8",
                            "value9",
                            "value4"
                        ],
                        [
                            "value10",
                            "value11",
                            "value12",
                            "value4"
                        ],
                        [
                            "value10",
                            "value11",
                            "value12",
                            "value4"
                        ],
                        [
                            "value10",
                            "value11",
                            "value12",
                            "value4"
                        ],
                        [
                            "value7",
                            "value8",
                            "value9",
                            "value4"
                        ],
                        [
                            "value10",
                            "value11",
                            "value12",
                            "value4"
                        ],
                        [
                            "value10",
                            "value11",
                            "value12",
                            "value4"
                        ],
                        [
                            "value10",
                            "value11",
                            "value12",
                            "value4"
                        ],
                        [
                            "value7",
                            "value8",
                            "value9",
                            "value4"
                        ],
                        [
                            "value10",
                            "value11",
                            "value12",
                            "value4"
                        ],
                        [
                            "value10",
                            "value11",
                            "value12",
                            "value4"
                        ],
                        [
                            "value10",
                            "value11",
                            "value12",
                            "value4"
                        ]
                    ]
                }
            ],

            tempScheme: [
                "internalID",
                "ID",
                "tag",
                "status"
            ]
        }
    }
})